title = "Vélostevie"
copyright = "Copyright © 2026 Stephen Masters"
enableGitInfo = true

baseURL = "https://example.com/"
canonifyURLs = false
enableEmoji = true
enableRobotsTXT = true
enableInlineShortcodes = true
summaryLength = 20

timeout = "180s"

languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[outputs]
  home = ["HTML", "RSS"]

[build]
  writeStats = true

[taxonomies]
  tag = "tags"

[pagination]
  pagerSize = 9

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true
  [privacy.x]
    disabled = false
    enableDNT = true
    simple = true
  [privacy.instagram]
    disabled = false
    simple = true
  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[minify]
  [minify.tdewolff.js]
    keepVarNames = true
    precision = 0
    version = 2022
  [minify.tdewolff.html]
    keepWhitespace = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.128.0"
  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    source = "data"
    target = "data"
  [[module.mounts]]
    source = "i18n"
    target = "i18n"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "static"
    target = "static"