baseURL = 'https://example.org/'
locale = 'en-gb'
title = 'Velostevie'
copyright = 'Copyright 2026 <a href="https://github.com/stephen-masters">Stephen Masters</a>.'
[module]
[[module.imports]]
  path = 'github.com/gethinode/hinode'
[[module.imports]]
  path = 'github.com/gethinode/mod-blocks'
